site_name: ADEpostLES Docs
theme:
  name: mkdocs
  color_mode: dark

nav:
  - index.md
  - installation.md
  - run.md
  - Configuration: namoptions.md
  - Utilities:
      - General: utilities
      - Generate Sources: utilities/gensources.md
      - PostProcess DALES: utilities/postprocesdales.md
      - Visualize Results: utilities/visualizations.md
